"""constraint check on reactions

Revision ID: 1c43e6882bc8
Revises: fc680ffdb3f2
Create Date: 2025-09-21 12:00:30.720231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c43e6882bc8'
down_revision: Union[str, Sequence[str], None] = 'fc680ffdb3f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_created_id_desc'), table_name='posts')
    op.create_index('ix_posts_created_id_desc', 'posts', ['date_created', 'id'], unique=False, postgresql_using='btree', postgresql_ops={'date_created': 'DESC', 'id': 'DESC'})
    op.drop_index(op.f('ux_reactions_user_comment_type'), table_name='reactions', postgresql_where='(comment_id IS NOT NULL)')
    op.drop_index(op.f('ux_reactions_user_post_type'), table_name='reactions', postgresql_where='(post_id IS NOT NULL)')
    op.create_unique_constraint('ux_reactions_user_target_type', 'reactions', ['user_id', 'type', 'post_id', 'comment_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ux_reactions_user_target_type', 'reactions', type_='unique')
    op.create_index(op.f('ux_reactions_user_post_type'), 'reactions', ['user_id', 'type', 'post_id'], unique=True, postgresql_where='(post_id IS NOT NULL)')
    op.create_index(op.f('ux_reactions_user_comment_type'), 'reactions', ['user_id', 'type', 'comment_id'], unique=True, postgresql_where='(comment_id IS NOT NULL)')
    op.drop_index('ix_posts_created_id_desc', table_name='posts', postgresql_using='btree', postgresql_ops={'date_created': 'DESC', 'id': 'DESC'})
    op.create_index(op.f('ix_posts_created_id_desc'), 'posts', [sa.literal_column('date_created DESC'), sa.literal_column('id DESC')], unique=False)
    # ### end Alembic commands ###
