"""chat modules

Revision ID: 358c6acd5432
Revises: 36fce617390b
Create Date: 2025-09-30 22:42:31.971299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '358c6acd5432'
down_revision: Union[str, Sequence[str], None] = '36fce617390b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('chat_type', sa.Enum('direct', 'group', name='roomtypeenum'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_public', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_rooms_date_created'), 'chat_rooms', ['date_created'], unique=False)
    op.create_index(op.f('ix_chat_rooms_id'), 'chat_rooms', ['id'], unique=False)
    op.create_index(op.f('ix_chat_rooms_name'), 'chat_rooms', ['name'], unique=True)
    op.create_table('chat_room_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chat_room_id', sa.Integer(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['chat_room_id'], ['chat_rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_room_members_date_created'), 'chat_room_members', ['date_created'], unique=False)
    op.create_index(op.f('ix_chat_room_members_id'), 'chat_room_members', ['id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('chat_room_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('edited', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['chat_room_id'], ['chat_rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_date_created'), 'messages', ['date_created'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_table('message_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_deliveries_date_created'), 'message_deliveries', ['date_created'], unique=False)
    op.create_index(op.f('ix_message_deliveries_id'), 'message_deliveries', ['id'], unique=False)
    op.create_index('ux_message_user', 'message_deliveries', ['message_id', 'user_id'], unique=True)
    op.drop_index(op.f('ix_posts_created_id_desc'), table_name='posts')
    op.create_index('ix_posts_created_id_desc', 'posts', ['date_created', 'id'], unique=False, postgresql_using='btree', postgresql_ops={'date_created': 'DESC', 'id': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_posts_created_id_desc', table_name='posts', postgresql_using='btree', postgresql_ops={'date_created': 'DESC', 'id': 'DESC'})
    op.create_index(op.f('ix_posts_created_id_desc'), 'posts', [sa.literal_column('date_created DESC'), sa.literal_column('id DESC')], unique=False)
    op.drop_index('ux_message_user', table_name='message_deliveries')
    op.drop_index(op.f('ix_message_deliveries_id'), table_name='message_deliveries')
    op.drop_index(op.f('ix_message_deliveries_date_created'), table_name='message_deliveries')
    op.drop_table('message_deliveries')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_date_created'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_chat_room_members_id'), table_name='chat_room_members')
    op.drop_index(op.f('ix_chat_room_members_date_created'), table_name='chat_room_members')
    op.drop_table('chat_room_members')
    op.drop_index(op.f('ix_chat_rooms_name'), table_name='chat_rooms')
    op.drop_index(op.f('ix_chat_rooms_id'), table_name='chat_rooms')
    op.drop_index(op.f('ix_chat_rooms_date_created'), table_name='chat_rooms')
    op.drop_table('chat_rooms')
    # ### end Alembic commands ###
