"""initial migration

Revision ID: 535a0bda0f7e
Revises: 
Create Date: 2025-09-02 23:15:04.634370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '535a0bda0f7e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_career_goals_id'), 'career_goals', ['id'], unique=False)
    op.create_table('industries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_industries_id'), 'industries', ['id'], unique=False)
    op.create_table('job_search_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_job_search_status_id'), 'job_search_status', ['id'], unique=False)
    op.create_table('new_role_value',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_new_role_value_id'), 'new_role_value', ['id'], unique=False)
    op.create_table('role_of_interest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_role_of_interest_id'), 'role_of_interest', ['id'], unique=False)
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_skills_id'), 'skills', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('nationality', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('profile_pic', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('user_type', sa.Enum('mentor', 'mentee', name='usertypeenum'), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('user_career_goals_assosciation',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('career_goals_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['career_goals_id'], ['career_goals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'career_goals_id')
    )
    op.create_table('user_industry_assosciation',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('industry_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'industry_id')
    )
    op.create_table('user_job_search_status_assosciation',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_search_status_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_search_status_id'], ['job_search_status.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'job_search_status_id')
    )
    op.create_table('user_new_role_assosciation',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('new_role_value_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['new_role_value_id'], ['new_role_value.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'new_role_value_id')
    )
    op.create_table('user_role_of_interest_assosciation',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_of_interest_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_of_interest_id'], ['role_of_interest.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_of_interest_id')
    )
    op.create_table('user_skills_assosciation',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skills_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['skills_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'skills_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_skills_assosciation')
    op.drop_table('user_role_of_interest_assosciation')
    op.drop_table('user_new_role_assosciation')
    op.drop_table('user_job_search_status_assosciation')
    op.drop_table('user_industry_assosciation')
    op.drop_table('user_career_goals_assosciation')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_skills_id'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_role_of_interest_id'), table_name='role_of_interest')
    op.drop_table('role_of_interest')
    op.drop_index(op.f('ix_new_role_value_id'), table_name='new_role_value')
    op.drop_table('new_role_value')
    op.drop_index(op.f('ix_job_search_status_id'), table_name='job_search_status')
    op.drop_table('job_search_status')
    op.drop_index(op.f('ix_industries_id'), table_name='industries')
    op.drop_table('industries')
    op.drop_index(op.f('ix_career_goals_id'), table_name='career_goals')
    op.drop_table('career_goals')
    # ### end Alembic commands ###
