"""add events table

Revision ID: 65918e7307eb
Revises: 358c6acd5432
Create Date: 2025-11-18 03:14:41.404420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65918e7307eb'
down_revision: Union[str, Sequence[str], None] = '358c6acd5432'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('end_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('start_time', sa.String(), nullable=False),
    sa.Column('end_time', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Add 'admin' value to UserTypeEnum
    op.execute("ALTER TYPE usertypeenum ADD VALUE IF NOT EXISTS 'admin'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Drop events table
    op.drop_table('events')
    
    # Note: Cannot remove enum value from PostgreSQL enum type directly
    # Would need to recreate the entire enum type
    # ### end Alembic commands ###
