"""uniqueness

Revision ID: 78079da5dd05
Revises: 39b095458dda
Create Date: 2025-04-28 17:09:46.881434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78079da5dd05'
down_revision: Union[str, None] = '39b095458dda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'career_goals', ['name'])
    op.create_unique_constraint(None, 'industries', ['name'])
    op.create_unique_constraint(None, 'job_search_status', ['name'])
    op.create_unique_constraint(None, 'new_role_value', ['name'])
    op.add_column('role_of_interest', sa.Column('category', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'role_of_interest', ['name'])
    op.create_unique_constraint(None, 'skills', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'skills', type_='unique')
    op.drop_constraint(None, 'role_of_interest', type_='unique')
    op.drop_column('role_of_interest', 'category')
    op.drop_constraint(None, 'new_role_value', type_='unique')
    op.drop_constraint(None, 'job_search_status', type_='unique')
    op.drop_constraint(None, 'industries', type_='unique')
    op.drop_constraint(None, 'career_goals', type_='unique')
    # ### end Alembic commands ###
