"""group creator

Revision ID: fc680ffdb3f2
Revises: e3c241a973d6
Create Date: 2025-09-19 20:50:44.550299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc680ffdb3f2'
down_revision: Union[str, Sequence[str], None] = 'e3c241a973d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_created_id_desc'), table_name='posts')
    op.create_index('ix_posts_created_id_desc', 'posts', ['date_created', 'id'], unique=False, postgresql_using='btree', postgresql_ops={'date_created': 'DESC', 'id': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_posts_created_id_desc', table_name='posts', postgresql_using='btree', postgresql_ops={'date_created': 'DESC', 'id': 'DESC'})
    op.create_index(op.f('ix_posts_created_id_desc'), 'posts', [sa.literal_column('date_created DESC'), sa.literal_column('id DESC')], unique=False)
    # ### end Alembic commands ###
